### ISSUE TITLE
$params['username'] not generated

### ISSUE THREAD

**Issue by betaman5577** [PUQ-sp-z-o-o/PUQ_WHMCS-Public-Nextcloud#1]
Hello,

Thank you for the module ;) 
the $params['username'] is not generated. How can i do ? Thank you in advance!

**Comment by puqcloud** [comment]
This is a parameter that is located in the server Nextcloud configuration in the WHMCS server admin panel.
WHMCS/admin->System Settings->Servers->SERVER_NEXTCLOUD->Username
